$cert = New-SelfSignedCertificate -Subject "MyCert" -Type CodeSigningCert -CertStoreLocation Cert:\LocalMachine\My
Export-Certificate -Cert $cert -FilePath "C:\temp\MyCert.crt"
Import-Certificate -CertStoreLocation "Cert:\LocalMachine\Root" -FilePath "C:\temp\MyCert.crt"
# SIG # Begin signature block
# MIIFUgYJKoZIhvcNAQcCoIIFQzCCBT8CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU+BpO2XDG1vIXZhU4fScVuQRR
# c3CgggL2MIIC8jCCAdqgAwIBAgIQZ0ak3mGIYKFHqzVEjTe30zANBgkqhkiG9w0B
# AQsFADARMQ8wDQYDVQQDDAZNeUNlcnQwHhcNMTkwMTE1MTAyOTI4WhcNMjAwMTE1
# MTA0OTI4WjARMQ8wDQYDVQQDDAZNeUNlcnQwggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQC8huxXdnZ9RymszJLwJXoRcxqDvyIXPuPn03mrzEk30fvLtf7M
# OUek+Sr5l85VtdKj0P6RCBt12KLeEqNrEXcqQoXH7c1FlNliIDhmq+qCda4FBP2K
# Wt7Px2NwXbqTGljSTsRvKRDMkDyZCRDQYt+rt5W+ugQzIgGtIKDGYXi83DZ3CO7i
# vhzZBBN6QvtXZM08wKCXir0W/nDfTpCBIkCffmmwtwujvfzwrZPJ8eyxEjtV0Avj
# tes+b62KlXe4yqFApETqaJdJbM4ghObklh10+dWcg0ceqhHRhJ6+ywsQrM6LvXjc
# 0GL8HYtHOAoiOigPsPWs7f6HaGxA+Evl6ot9AgMBAAGjRjBEMA4GA1UdDwEB/wQE
# AwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUTEQmlMsena556vUy
# u1Cqa6g+mCkwDQYJKoZIhvcNAQELBQADggEBAF9jZPd90qjR4uia0FeTnNbxwBra
# LtYw5t5pADjCTOhVd6TgKGqTB8LcOeiB4YEX83B3x3THM9FGkLakHjzYtXUddz5M
# S2ZzTMMihNLcJiyKMHl5TiBHVMYPdf/JRtQj/mqAfaIdbbhSq8E7eGYS2RJwxjS4
# zJjFakBHvwPYAdQzIFVwMTLcMV6l8mRRFykWWsTA99az3r018mX2X33i6YShnWIP
# AbcdGJeUydtOq17azuZsN3ssBlKhNSAOkpEhKGR1dyT4mb3Rtxmd0rB3MlxueH5Q
# C4XHlLnn2/QliGLP5SzyMziZ2/threeTglGxM5qQ1C4oeaGC4vcdMEN0N/UxggHG
# MIIBwgIBATAlMBExDzANBgNVBAMMBk15Q2VydAIQZ0ak3mGIYKFHqzVEjTe30zAJ
# BgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0B
# CQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAj
# BgkqhkiG9w0BCQQxFgQUZG0bDK+g+LzY5npCp/JxUKHbiRwwDQYJKoZIhvcNAQEB
# BQAEggEAMH7U4qrjhzOJkEMTwHSPfv6u11GnbcM9JU9HPMp+SstAeQqVDex8QPNF
# 7NiYtT+DqpH/h6ZLR2McZ1bAwbnueqVobKCo+NgwrwwzeGDtvjMJz7IABvd+WE+h
# RfZgTr82/M+PWovmc/+gGl6MMLJmWvG9d6k5LrJ0s9NrEM+LVr7s8dHj5xhRO9s+
# +EUE75Sc2Iy/iJUraBJwpcxzlrI2rioxrvJ+QEl2bJ30AMfb2832PZvBjb+zZtrJ
# RmmB9oZUOUgaFFlwdML4MH+RLfiXj8nXikRpDjHYoyYeL8Bwy1pwDdMM+HTi8MoU
# yANVoKrJWjhb6EzcTd1MT5qNjh2fig==
# SIG # End signature block