Install-Module -Name Lability
Set-LabHostDefault -ConfigurationPath C:\Lability\Configurations
Set-LabHostDefault -DifferencingVhdPath C:\Lability\VHD
Set-LabHostDefault -HotfixPath C:\Lability\Hotfixes
Set-LabHostDefault -ParentVhdPath C:\Lability\ParentVHD
Set-LabHostDefault -IsoPath C:\Lability\ISO
Set-LabHostDefault -ResourcePath C:\Lability\
Set-LabHostDefault -ConfigurationPath C:\Lability\Configurations
Set-LabHostDefault -DifferencingVhdPath C:\Lability\VHD
Set-LabHostDefault -HotfixPath C:\Lability\Hotfixes
Set-LabHostDefault -ParentVhdPath C:\Lability\ParentVHD
Set-LabHostDefault -IsoPath C:\ISO
Set-LabHostDefault -ResourcePath C:\Lability\